services:
  ############################################# FRONTEND REACT ######################################################
  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # force le polling
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  ################################################### BACKEND NEST ####################################################
  nest:
    container_name: nest-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.nest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Variables pour DB
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - MONGO_HOST=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
    depends_on:
      - postgres
      - mongo
    command: ["npm", "run", "start:nest"]

  #################################################### BACKEND EXPRESS ############################################
  express:
    container_name: express-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.express
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Variables pour DB
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - MONGO_HOST=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
    depends_on:
      - postgres
      - mongo
    command: ["npm", "run", "start:express"]

    ################################################ POSTGRES ##########################################################
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ########################################################## MONGO #####################################################
  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword

volumes:
  postgres_data:
  mongo_data:
